version: '0.2'

networks:
    datapipeline:
        driver: bridge
services:
  kafka:
    image: apache/kafka:latest
    networks:
      - datapipeline
    ports:
      - 9092:9092
      - 29092:29092

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - datapipeline
